### PR TITLE
fix: full swap reverse test

### PR DESCRIPTION
**Pull request by joshualyguessennd**
- fix test_reverse_swap_scenario

### CODE REVIEW

**Comment by Genysys** [comment]
LGTM

**Comment by Genysys** [comment]
Can you please investigate why these warnings show up in the tests?


```
tests/properties/yearnV1/test_properties_v1.py::test_deposit_unpause_vault_reverts
tests/yearnV1/test_yearnV1.py::test_deactivate_vault
  /Users/samueldare/Library/Python/3.9/lib/python/site-packages/brownie/network/contract.py:779: BrownieEnvironmentWarning: 'yTestVault' defines a 'balance' function, 'yTestVault.balance' is unavailable
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by joshualyguessennd** [comment]
> Can you please investigate why these warnings show up in the tests?
> 
> ```
> tests/properties/yearnV1/test_properties_v1.py::test_deposit_unpause_vault_reverts
> tests/yearnV1/test_yearnV1.py::test_deactivate_vault
>   /Users/samueldare/Library/Python/3.9/lib/python/site-packages/brownie/network/contract.py:779: BrownieEnvironmentWarning: 'yTestVault' defines a 'balance' function, 'yTestVault.balance' is unavailable
>     warnings.warn(
> 
> -- Docs: https://docs.pytest.org/en/stable/warnings.html
> ```

it's related to the brownie YtestVault integrated plugin. don't think it's an issue for our code

**Comment by Genysys** [comment]
LGTM

**Pull request merged**
